version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/voting_system

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting_system
    ports:
      - "5432:5432"
